# Generated by Django 5.1.2 on 2024-11-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrialSystem', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='foodDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='foodType',
            field=models.CharField(max_length=200),
        ),
    ]
